services:
  ubeninmar-bot:
    build: .
    container_name: ubeninmar-telegram-bot
    image: cchacin/ubeninmar-telegram-bot:latest
    environment:
      # Telegram Bot Token - Set this in your .env file or export before running
      - BOT_TOKEN=${BOT_TOKEN}
      - AFFILIATE_TAG=${AFFILIATE_TAG}
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ${HOME}/.m2:/root/.m2